### ISSUE TITLE
Doesn't work the first time, now works but only lets me play as alex

### ISSUE THREAD

**Issue by Sonic3Modder** [FabricMC/.github#2]
I was starting to play Minecraft but then I got an error then It ran but only works as alex, I tried to relaunch the launcher and remove all mods and I got this error
![Screenshot 2024-05-25 145248](https://github.com/FabricMC/.github/assets/153376854/b6f2985e-43c1-4abc-b6ec-8dead16f2737)

**Comment by modmuss50** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
