### ISSUE TITLE
⬇️

### ISSUE THREAD

**Issue by Sonic3Modder** [FabricMC/.github#3]
https://github.com/FabricMC/.github/issues/2#issue-2317186865

**Comment by modmuss50** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.

**Comment by Sonic3Modder** [comment]
Why, my parents won't let me use discord.

**Comment by Sonic3Modder** [comment]
So I can't post their, this was the only place I thought of.
